# Generated by Django 6.0.1 on 2026-01-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HR", "HR"),
                            ("ENGINEERING", "ENGINEERING"),
                            ("SALES", "SALES"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MANAGER", "MANAGER"),
                            ("DEVELOPER", "DEVELOPER"),
                            ("ANALYST", "ANALYST"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
